#region

using Imperium.Core;
using Imperium.MonoBehaviours.ImpUI.Common;
using Imperium.Types;

#endregion

namespace Imperium.MonoBehaviours.ImpUI.VisualizerUi.Windows;

internal class VisualizersWindows : BaseWindow
{
    protected override void RegisterWindow()
    {
        ImpToggle.Bind(
            "Colliders/Employees",
            content,
            ImpSettings.Visualizations.Employees,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Entities",
            content,
            ImpSettings.Visualizations.Entities,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/MapHazards",
            content,
            ImpSettings.Visualizations.MapHazards,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Props",
            content,
            ImpSettings.Visualizations.Props,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Vents",
            content,
            ImpSettings.Visualizations.Vents,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Foliage",
            content,
            ImpSettings.Visualizations.Foliage,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/TileBorders",
            content,
            ImpSettings.Visualizations.TileBorders,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/InteractTriggers",
            content,
            ImpSettings.Visualizations.InteractTriggers,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/ScrapSpawns",
            content,
            ImpSettings.Visualizations.ScrapSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesIndoor",
            content,
            ImpSettings.Visualizations.AINodesIndoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesOutdoor",
            content,
            ImpSettings.Visualizations.AINodesOutdoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/SpawnDenialPoints",
            content,
            ImpSettings.Visualizations.SpawnDenialPoints,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/BeeSpawns",
            content,
            ImpSettings.Visualizations.BeeSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpawnIndicators",
            content,
            ImpSettings.Visualizations.SpawnIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpawnTimers",
            content,
            ImpSettings.Visualizations.VentTimers,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/NoiseIndicators",
            content,
            ImpSettings.Visualizations.NoiseIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "CastingIndicators/Shotguns",
            content,
            ImpSettings.Visualizations.ShotgunIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "CastingIndicators/Shovels",
            content,
            ImpSettings.Visualizations.ShovelIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "CastingIndicators/Knives",
            content,
            ImpSettings.Visualizations.KnifeIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "CastingIndicators/Landmines",
            content,
            ImpSettings.Visualizations.LandmineIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "CastingIndicators/SpikeTraps",
            content,
            ImpSettings.Visualizations.SpikeTrapIndicators,
            themeBinding
        );
    }

    protected override void OnThemeUpdate(ImpTheme theme)
    {
        ImpThemeManager.Style(
            theme,
            content,
            new StyleOverride("Separator", Variant.DARKER)
        );
    }
}