#region

using Imperium.Core;
using Imperium.MonoBehaviours.ImpUI.Common;

#endregion

namespace Imperium.MonoBehaviours.ImpUI.VisualizationUI.Windows;

internal class VisualizersWindows : BaseWindow
{
    protected override void RegisterWindow()
    {
        ImpToggle.Bind(
            "Colliders/Employees",
            content,
            ImpSettings.Visualizations.Employees,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Entities",
            content,
            ImpSettings.Visualizations.Entities,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/MapHazards",
            content,
            ImpSettings.Visualizations.MapHazards,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Props",
            content,
            ImpSettings.Visualizations.Props,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Foliage",
            content,
            ImpSettings.Visualizations.Foliage,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/TileBorders",
            content,
            ImpSettings.Visualizations.TileBorders,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Room",
            content,
            ImpSettings.Visualizations.Room,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Colliders",
            content,
            ImpSettings.Visualizations.Colliders,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Triggers",
            content,
            ImpSettings.Visualizations.Triggers,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PhysicsObject",
            content,
            ImpSettings.Visualizations.PhysicsObject,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/NavigationSurface",
            content,
            ImpSettings.Visualizations.NavigationSurface,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/InteractTriggers",
            content,
            ImpSettings.Visualizations.InteractTriggers,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/RoomLight",
            content,
            ImpSettings.Visualizations.RoomLight,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Anomaly",
            content,
            ImpSettings.Visualizations.Anomaly,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Railing",
            content,
            ImpSettings.Visualizations.Railing,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PlacementBlocker",
            content,
            ImpSettings.Visualizations.PlacementBlocker,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Terrain",
            content,
            ImpSettings.Visualizations.Terrain,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PlaceableShipObjects",
            content,
            ImpSettings.Visualizations.PlaceableShipObjects,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/MiscLevelGeometry",
            content,
            ImpSettings.Visualizations.MiscLevelGeometry,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/ScanNodes",
            content,
            ImpSettings.Visualizations.ScanNode,
            themeBinding
        );

        ImpToggle.Bind(
            "Overlays/Vents",
            content,
            ImpSettings.Visualizations.Vents,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/ScrapSpawns",
            content,
            ImpSettings.Visualizations.ScrapSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesIndoor",
            content,
            ImpSettings.Visualizations.AINodesIndoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesOutdoor",
            content,
            ImpSettings.Visualizations.AINodesOutdoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/SpawnDenialPoints",
            content,
            ImpSettings.Visualizations.SpawnDenialPoints,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/BeeSpawns",
            content,
            ImpSettings.Visualizations.BeeSpawns,
            themeBinding
        );

        ImpToggle.Bind(
            "Gizmos/SpawnIndicators",
            content,
            ImpSettings.Visualizations.SpawnIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpawnTimers",
            content,
            ImpSettings.Visualizations.VentTimers,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/NoiseIndicators",
            content,
            ImpSettings.Visualizations.NoiseIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Shotguns",
            content,
            ImpSettings.Visualizations.ShotgunIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Shovels",
            content,
            ImpSettings.Visualizations.ShovelIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Knives",
            content,
            ImpSettings.Visualizations.KnifeIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Landmines",
            content,
            ImpSettings.Visualizations.LandmineIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpikeTraps",
            content,
            ImpSettings.Visualizations.SpikeTrapIndicators,
            themeBinding
        );
    }
}