#region

using Imperium.MonoBehaviours.ImpUI.Common;

#endregion

namespace Imperium.MonoBehaviours.ImpUI.VisualizationUI.Windows;

internal class VisualizersWindows : BaseWindow
{
    protected override void RegisterWindow()
    {
        ImpToggle.Bind(
            "Colliders/Employees",
            content,
            Imperium.Settings.Visualization.Employees,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Entities",
            content,
            Imperium.Settings.Visualization.Entities,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/MapHazards",
            content,
            Imperium.Settings.Visualization.MapHazards,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Props",
            content,
            Imperium.Settings.Visualization.Props,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Foliage",
            content,
            Imperium.Settings.Visualization.Foliage,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/TileBorders",
            content,
            Imperium.Settings.Visualization.TileBorders,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Room",
            content,
            Imperium.Settings.Visualization.Room,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Colliders",
            content,
            Imperium.Settings.Visualization.Colliders,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Triggers",
            content,
            Imperium.Settings.Visualization.Triggers,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PhysicsObject",
            content,
            Imperium.Settings.Visualization.PhysicsObject,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/InteractTriggers",
            content,
            Imperium.Settings.Visualization.InteractTriggers,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/RoomLight",
            content,
            Imperium.Settings.Visualization.RoomLight,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Anomaly",
            content,
            Imperium.Settings.Visualization.Anomaly,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Railing",
            content,
            Imperium.Settings.Visualization.Railing,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PlacementBlocker",
            content,
            Imperium.Settings.Visualization.PlacementBlocker,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/Terrain",
            content,
            Imperium.Settings.Visualization.Terrain,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/PlaceableShipObjects",
            content,
            Imperium.Settings.Visualization.PlaceableShipObjects,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/MiscLevelGeometry",
            content,
            Imperium.Settings.Visualization.MiscLevelGeometry,
            themeBinding
        );
        ImpToggle.Bind(
            "Colliders/ScanNodes",
            content,
            Imperium.Settings.Visualization.ScanNode,
            themeBinding
        );

        ImpToggle.Bind(
            "Overlays/Vents",
            content,
            Imperium.Settings.Visualization.Vents,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/ScrapSpawns",
            content,
            Imperium.Settings.Visualization.ScrapSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/HazardSpawns",
            content,
            Imperium.Settings.Visualization.HazardSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesIndoor",
            content,
            Imperium.Settings.Visualization.AINodesIndoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/AINodesOutdoor",
            content,
            Imperium.Settings.Visualization.AINodesOutdoor,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/SpawnDenialPoints",
            content,
            Imperium.Settings.Visualization.SpawnDenialPoints,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/BeeSpawns",
            content,
            Imperium.Settings.Visualization.BeeSpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/OutsideEntitySpawns",
            content,
            Imperium.Settings.Visualization.OutsideEntitySpawns,
            themeBinding
        );
        ImpToggle.Bind(
            "Overlays/NavMeshSurfaces",
            content,
            Imperium.Settings.Visualization.NavMeshSurfaces,
            themeBinding
        );

        ImpToggle.Bind(
            "Gizmos/SpawnIndicators",
            content,
            Imperium.Settings.Visualization.SpawnIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpawnTimers",
            content,
            Imperium.Settings.Visualization.VentTimers,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/NoiseIndicators",
            content,
            Imperium.Settings.Visualization.NoiseIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Shotguns",
            content,
            Imperium.Settings.Visualization.ShotgunIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Shovels",
            content,
            Imperium.Settings.Visualization.ShovelIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Knives",
            content,
            Imperium.Settings.Visualization.KnifeIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/Landmines",
            content,
            Imperium.Settings.Visualization.LandmineIndicators,
            themeBinding
        );
        ImpToggle.Bind(
            "Gizmos/SpikeTraps",
            content,
            Imperium.Settings.Visualization.SpikeTrapIndicators,
            themeBinding
        );
    }
}