[config]
schemaVersion = "0.0.1"

[package]
namespace = "giosuel"
name = "Imperium"
description = "A powerful and highly performant all-in-one debugging tool to test and explore game mechanics and functionality in Lethal Company."
websiteUrl = "https://github.com/giosuel/Imperium"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
NicholaScott.BepInEx.RuntimeNetcodeRPCValidator-RuntimeNetcodeRPCValidator = "0.2.5"

[build]
icon = "icon_256x256.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../Imperium/bin/Release/netstandard2.1/giosuel.Imperium.dll"
target = "/BepInEx/plugins/giosuel.Imperium/"

[[build.copy]]
source = "../assets/imperium_assets"
target = "/BepInEx/plugins/giosuel.Imperium/"

[publish]
communities = [ "lethal-company", ]
repository = "https://thunderstore.io"
[publish.categories]
lethal-company = [ "bepinex", "mods", "tools", "serverside", "clientside", "misc" ]