#region

using Imperium.Interface.Common;

#endregion

namespace Imperium.Interface.ImperiumUI.Windows.Visualization.Widgets;

internal class Visualizers : ImpWidget
{
    protected override void InitWidget()
    {
        ImpToggle.Bind(
            "Colliders/Employees",
            transform,
            Imperium.Settings.Visualization.Employees,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Entities",
            transform,
            Imperium.Settings.Visualization.Entities,
            theme
        );
        ImpToggle.Bind(
            "Colliders/MapHazards",
            transform,
            Imperium.Settings.Visualization.MapHazards,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Props",
            transform,
            Imperium.Settings.Visualization.Props,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Foliage",
            transform,
            Imperium.Settings.Visualization.Foliage,
            theme
        );
        ImpToggle.Bind(
            "Colliders/TileBorders",
            transform,
            Imperium.Settings.Visualization.TileBorders,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Room",
            transform,
            Imperium.Settings.Visualization.Room,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Colliders",
            transform,
            Imperium.Settings.Visualization.Colliders,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Triggers",
            transform,
            Imperium.Settings.Visualization.Triggers,
            theme
        );
        ImpToggle.Bind(
            "Colliders/PhysicsObject",
            transform,
            Imperium.Settings.Visualization.PhysicsObject,
            theme
        );
        ImpToggle.Bind(
            "Colliders/InteractTriggers",
            transform,
            Imperium.Settings.Visualization.InteractTriggers,
            theme
        );
        ImpToggle.Bind(
            "Colliders/RoomLight",
            transform,
            Imperium.Settings.Visualization.RoomLight,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Anomaly",
            transform,
            Imperium.Settings.Visualization.Anomaly,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Railing",
            transform,
            Imperium.Settings.Visualization.Railing,
            theme
        );
        ImpToggle.Bind(
            "Colliders/PlacementBlocker",
            transform,
            Imperium.Settings.Visualization.PlacementBlocker,
            theme
        );
        ImpToggle.Bind(
            "Colliders/Terrain",
            transform,
            Imperium.Settings.Visualization.Terrain,
            theme
        );
        ImpToggle.Bind(
            "Colliders/PlaceableShipObjects",
            transform,
            Imperium.Settings.Visualization.PlaceableShipObjects,
            theme
        );
        ImpToggle.Bind(
            "Colliders/MiscLevelGeometry",
            transform,
            Imperium.Settings.Visualization.MiscLevelGeometry,
            theme
        );
        ImpToggle.Bind(
            "Colliders/ScanNodes",
            transform,
            Imperium.Settings.Visualization.ScanNode,
            theme
        );

        ImpToggle.Bind(
            "Overlays/Vents",
            transform,
            Imperium.Settings.Visualization.Vents,
            theme
        );
        ImpToggle.Bind(
            "Overlays/ScrapSpawns",
            transform,
            Imperium.Settings.Visualization.ScrapSpawns,
            theme
        );
        ImpToggle.Bind(
            "Overlays/HazardSpawns",
            transform,
            Imperium.Settings.Visualization.HazardSpawns,
            theme
        );
        ImpToggle.Bind(
            "Overlays/AINodesIndoor",
            transform,
            Imperium.Settings.Visualization.AINodesIndoor,
            theme
        );
        ImpToggle.Bind(
            "Overlays/AINodesOutdoor",
            transform,
            Imperium.Settings.Visualization.AINodesOutdoor,
            theme
        );
        ImpToggle.Bind(
            "Overlays/SpawnDenialPoints",
            transform,
            Imperium.Settings.Visualization.SpawnDenialPoints,
            theme
        );
        ImpToggle.Bind(
            "Overlays/BeeSpawns",
            transform,
            Imperium.Settings.Visualization.BeeSpawns,
            theme
        );
        ImpToggle.Bind(
            "Overlays/OutsideEntitySpawns",
            transform,
            Imperium.Settings.Visualization.OutsideEntitySpawns,
            theme
        );
        ImpToggle.Bind(
            "Overlays/NavMeshSurfaces",
            transform,
            Imperium.Settings.Visualization.NavMeshSurfaces,
            theme
        );

        ImpToggle.Bind(
            "Gizmos/SpawnIndicators",
            transform,
            Imperium.Settings.Visualization.SpawnIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/SpawnTimers",
            transform,
            Imperium.Settings.Visualization.VentTimers,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/NoiseIndicators",
            transform,
            Imperium.Settings.Visualization.NoiseIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/Shotguns",
            transform,
            Imperium.Settings.Visualization.ShotgunIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/Shovels",
            transform,
            Imperium.Settings.Visualization.ShovelIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/Knives",
            transform,
            Imperium.Settings.Visualization.KnifeIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/Landmines",
            transform,
            Imperium.Settings.Visualization.LandmineIndicators,
            theme
        );
        ImpToggle.Bind(
            "Gizmos/SpikeTraps",
            transform,
            Imperium.Settings.Visualization.SpikeTrapIndicators,
            theme
        );
    }
}